# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pfafsteter
                                 A QGIS plugin
 Codificação de bacias hidrográficas pelo método de Otto Pfafsteter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-12
        copyright            : (C) 2022 by Claudio Bielenki Jr
        email                : bielenki@ufscar.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pfafsteter class from file pfafsteter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pfafsteterTools import pfafsteter
    return pfafsteter(iface)
